"""R-007 competitor matrix data (03_COMPETITOR_MATRIX.csv).

Each row is judged by HOW IT CAUSES US TO LOSE, not by logo presence (work order §2.11, §14).
Cells without evidence are UNKNOWN. A cell that says 'not found' means a search was run and
nothing was found (no path found ≠ does not exist). Evidence IDs point to 02_EVIDENCE_LEDGER.csv.
"""

FIELDS = ["competitor_id", "name", "class", "geography", "user_scale", "paid_users", "subscription_detection",
          "cross_provider_coverage", "cancel_instructions", "cancel_on_behalf", "bill_negotiation", "verification",
          "bank_linking", "email_linking", "price", "business_model", "distribution", "moat", "japan_status",
          "evidence_strength", "how_we_lose", "cheapest_credible_response_if_we_succeed", "response_cost_and_speed",
          "evidence_ids"]

U = "UNKNOWN"
NF = "not found"

ROWS = [
    dict(competitor_id="CM01", name="Money Forward ME", **{"class": "JP PFM incumbent"}, geography="Japan",
         user_scale="17.3M users (Oct 2025; registered, not MAU)", paid_users=U,
         subscription_detection="Premium 'サブスクレポート' from card/bank statements; App Store and carrier billing explicitly not supported",
         cross_provider_coverage="Named video, music, game, book/news and shopping services (count UNKNOWN)", cancel_instructions=NF,
         cancel_on_behalf=NF, bill_negotiation="No negotiation found; runs fixed-cost review and switching (insurance, electricity, internet, phone) and own electricity retail",
         verification="None as a feature; next month's statement implicitly", bank_linking="Yes (core product)", email_linking=U,
         price="Premium ¥540/month or ¥5,940/year (card); ¥590/¥6,490 via app stores (from 2025-08-05)",
         business_model="Consumer premium plus fixed-cost switching and referral (MF でんき)", distribution="Own app base; listed company",
         moat="Aggregation connections, data scale and brand (classification: distribution and data advantage; not tested here)",
         japan_status="Active", evidence_strength="company-reported (help pages, IR extract); not opened",
         how_we_lose="It already holds the detection (J1) for card/bank rails and the user relationship for 17.3M people. A cancel guide or deep link next to the existing サブスクレポート matches C02/C03 for its base at near-zero marginal cost, and it can monetise switching (C08) without us.",
         cheapest_credible_response_if_we_succeed="Add a per-service 'how to cancel' link and a reminder beside each detected subscription; later, partner with or acquire a concierge for hard routes.",
         response_cost_and_speed="Low; weeks to months (content plus UI on an existing feature). An inference, not a company statement.",
         evidence_ids="R7-E-G01;R7-E-G02;R7-E-G03;R7-E-G04"),
    dict(competitor_id="CM02", name="Moneytree / Moneytree Grow (MUFG Bank subsidiary since 2025-08-29)", **{"class": "JP PFM incumbent and aggregator (bank-owned)"},
         geography="Japan", user_scale="About 6.5M users (2025)", paid_users=U,
         subscription_detection="Grow 'サブスク一覧': monthly list of automatically retrieved subscription payments (amount, date, method)",
         cross_provider_coverage=U, cancel_instructions=NF, cancel_on_behalf=NF, bill_negotiation=NF, verification=U,
         bank_linking="Yes; MT LINK aggregates 2,500-2,700+ institutions", email_linking=U, price="Grow ¥360/month or ¥3,600/year",
         business_model="Consumer premium; MT LINK enterprise API (43 enterprise clients, dated)", distribution="Own app; MUFG 'emot' bank channel",
         moat="Regulated aggregation infrastructure plus bank ownership (distribution and infrastructure advantage)", japan_status="Active",
         evidence_strength="company-reported plus secondary; help page content not seen",
         how_we_lose="Its owner MUFG is the most natural Japanese B2B2C buyer and already owns the list and the aggregation pipe. A startup that needed MT LINK would depend on a competitor-owned pipe.",
         cheapest_credible_response_if_we_succeed="Put the subscription list plus 'cancel' guidance into MUFG's bank app (emot).",
         response_cost_and_speed="Low to medium; bank release cycles are slow (months to a year). Inference.",
         evidence_ids="R7-E-G05;R7-E-G06;R7-E-G07;R7-E-G08"),
    dict(competitor_id="CM03", name="Zaim", **{"class": "JP PFM incumbent"}, geography="Japan", user_scale="11M+ downloads (not users)", paid_users=U,
         subscription_detection="Extracts recurring payments from records; predicts due dates and plans", cross_provider_coverage=U, cancel_instructions=NF,
         cancel_on_behalf=NF, bill_negotiation=NF, verification=U, bank_linking="Yes (PFM)", email_linking=U, price="Premium ¥4,800/year (2025)",
         business_model="Consumer premium; partnerships", distribution="Own app", moat=U, japan_status="Active",
         evidence_strength="company-reported (PR)", how_we_lose="A third free or cheap J1 tracker sets the consumer price expectation for tracking near zero.",
         cheapest_credible_response_if_we_succeed="As CM01.", response_cost_and_speed="Low. Inference.", evidence_ids="R7-E-G09"),
    dict(competitor_id="CM04", name="Apple App Store subscriptions", **{"class": "Platform (billing-rail owner)"}, geography="Global incl. Japan", user_scale=U,
         paid_users="n/a", subscription_detection="Complete for Apple-billed subscriptions (the user's own list)",
         cross_provider_coverage="All App Store-billed apps; none outside Apple billing",
         cancel_instructions="In-product: Settings → Apple ID → Subscriptions → Cancel", cancel_on_behalf="Only the user or Apple support; developers cannot cancel",
         bill_negotiation="n/a", verification="UNKNOWN (expiry shown in list, not verified here)", bank_linking="n/a", email_linking="n/a", price="Free",
         business_model="Commission on app sales", distribution="Every iPhone", moat="Owns the billing rail and the device", japan_status="Active",
         evidence_strength="secondary and community extracts; Apple pages not opened",
         how_we_lose="For Apple-billed subscriptions the job is already solved free and in-ecosystem, and no third party can execute. Stop condition 1 for this rail.",
         cheapest_credible_response_if_we_succeed="None needed.", response_cost_and_speed="n/a",
         evidence_ids="R7-E-B01;R7-E-B04;R7-E-G29"),
    dict(competitor_id="CM05", name="Google Play subscriptions", **{"class": "Platform (billing-rail owner)"}, geography="Global incl. Japan", user_scale=U, paid_users="n/a",
         subscription_detection="Complete for Play-billed subscriptions", cross_provider_coverage="All Play-billed apps", cancel_instructions="In-product (Play subscriptions)",
         cancel_on_behalf="The developer can cancel via API; no third-party route found", bill_negotiation="n/a", verification=U, bank_linking="n/a", email_linking="n/a",
         price="Free", business_model="Commission", distribution="Android devices", moat="Owns the billing rail", japan_status="Active",
         evidence_strength="company-reported (developer docs extract)",
         how_we_lose="For Play-billed subscriptions the job is solved free in Play, and only the developer has a programmatic cancel. Stop condition 1 for this rail.", cheapest_credible_response_if_we_succeed="None needed.", response_cost_and_speed="n/a",
         evidence_ids="R7-E-B03;R7-E-D02"),
    dict(competitor_id="CM06", name="Amazon.co.jp Memberships & Subscriptions", **{"class": "Platform (merchant with its own subscription hub)"}, geography="Japan", user_scale=U,
         paid_users="n/a", subscription_detection="Amazon-billed subscriptions incl. Prime Video channels", cross_provider_coverage="Amazon-billed only",
         cancel_instructions="In-product list; channels via browser only", cancel_on_behalf=NF, bill_negotiation="n/a", verification=U, bank_linking="n/a",
         email_linking="n/a", price="Free", business_model="Retail and subscriptions", distribution="Amazon customers", moat="Owns the billing rail", japan_status="Active",
         evidence_strength="secondary", how_we_lose="Amazon-billed subscriptions already have a free central list and cancel surface.",
         cheapest_credible_response_if_we_succeed="None needed.", response_cost_and_speed="n/a", evidence_ids="R7-E-G28"),
    dict(competitor_id="CM07", name="Carrier billing portals (docomo, au, SoftBank)", **{"class": "Telco (billing-rail owner)"}, geography="Japan", user_scale=U,
         paid_users="n/a", subscription_detection="Continuous-charge list in each carrier portal", cross_provider_coverage="Carrier-billed content only",
         cancel_instructions="Portal links to the provider (docomo); au may cancel in the list (conflicting)", cancel_on_behalf=NF, bill_negotiation="n/a",
         verification="List status (UNKNOWN whether it updates)", bank_linking="n/a", email_linking="n/a", price="Free", business_model="Billing fee (UNKNOWN)",
         distribution="Every subscriber", moat="Owns the rail and the identity", japan_status="Active", evidence_strength="company-reported plus secondary how-to",
         how_we_lose="Carrier-billed subscriptions are visible to the user free in the carrier portal and invisible to card-based detection, so a startup adds little on this rail without the user's carrier login.",
         cheapest_credible_response_if_we_succeed="Make the continuous-charge list more prominent; add in-list cancel for all.", response_cost_and_speed="Low. Inference.",
         evidence_ids="R7-E-B02;R7-E-B06"),
    dict(competitor_id="CM08", name="Japanese card issuers and bank apps (SMBC Olive/Vpass, JCB, Rakuten Card, etc.)", **{"class": "Payer-side incumbents"}, geography="Japan",
         user_scale=U, paid_users="n/a", subscription_detection="No subscription-list feature found in extracts (MUFG via Moneytree is CM02)", cross_provider_coverage=U,
         cancel_instructions=NF, cancel_on_behalf=NF, bill_negotiation="n/a", verification=U, bank_linking="Own data", email_linking="n/a", price=U,
         business_model="Interchange, fees", distribution="Card and bank customers", moat="Own the transaction data and the customer", japan_status="Feature not found (search incomplete)",
         evidence_strength="not found (one search)",
         how_we_lose="They hold first-party transaction data and the dispute process. If they adopt network tooling (CM09), cancellation lands where the charge is paid, without a startup.",
         cheapest_credible_response_if_we_succeed="License network tooling (Visa/Mastercard) or Moneytree's list.", response_cost_and_speed="Medium; months to a year. Inference.",
         evidence_ids="R7-E-G25;R7-E-G26"),
    dict(competitor_id="CM09", name="Card networks: Visa Enhanced Subscription Manager (with Pinwheel); Mastercard Subscriptions Control / Smart Subscriptions", **{"class": "Network infrastructure for issuers"},
         geography="North America (Visa from summer 2026; LatAm later); US (Mastercard)", user_scale="n/a", paid_users="n/a",
         subscription_detection="Issuer-side recurring-payment view", cross_provider_coverage="Visa/Pinwheel: 100+ or 150+ merchants for switch/cancel",
         cancel_instructions="Guided cancellation for some merchants", cancel_on_behalf="Cancellation inside the banking app for integrated merchants (mechanism partly guided)",
         bill_negotiation="n/a", verification=U, bank_linking="Issuer-native", email_linking="n/a", price="B2B (UNKNOWN)", business_model="Network services to issuers",
         distribution="Issuers' apps", moat="Network position and merchant integrations", japan_status="Not announced for Japan (not found)",
         evidence_strength="company-reported (Visa); secondary (Mastercard)",
         how_we_lose="It defines the B2B2C category globally. A Japanese issuer evaluating C07 can wait for its network's product, with an explicit motive: fewer disputes and chargebacks.",
         cheapest_credible_response_if_we_succeed="Extend rollout to Japanese issuers.", response_cost_and_speed="Medium; regional rollout. Inference.",
         evidence_ids="R7-E-G25;R7-E-G26"),
    dict(competitor_id="CM10", name="サブトラ", **{"class": "JP subscription tracker (e-mail-based)"}, geography="Japan", user_scale=U, paid_users=U,
         subscription_detection="Gmail payment-mail detection; AI savings suggestions (unused, duplicate, price rise)", cross_provider_coverage=U, cancel_instructions=U,
         cancel_on_behalf=NF, bill_negotiation="n/a", verification=U, bank_linking="No (per blog)", email_linking="Yes (Gmail)", price="¥280/month, ¥2,200/year, ¥4,800 one-off",
         business_model="Consumer subscription", distribution="App stores", moat=U, japan_status="Active (per 2026-08 blog)", evidence_strength="secondary (blog)",
         how_we_lose="It anchors e-mail-based J1 at ¥280 a month and shows the Gmail route is workable for a small team.",
         cheapest_credible_response_if_we_succeed="Add cancel guides.", response_cost_and_speed="Low. Inference.", evidence_ids="R7-E-G10;R7-E-D01"),
    dict(competitor_id="CM11", name="Subcut", **{"class": "Subscription tracker (statement-based; foreign)"}, geography="US storefront; Japan coverage UNKNOWN", user_scale=U, paid_users=U,
         subscription_detection="Bank and card statements", cross_provider_coverage=U, cancel_instructions="Markets 'cancel' (mechanism UNKNOWN)", cancel_on_behalf=U,
         bill_negotiation=U, verification=U, bank_linking="Yes (market UNKNOWN)", email_linking=U, price="$1.99/month, $9.99/year, $14.99 lifetime",
         business_model="Consumer subscription", distribution="App stores", moat=U, japan_status=U, evidence_strength="app-store listing (US) plus blog",
         how_we_lose="A low-price import could cover J1 and J3 if it supports Japanese banks (UNKNOWN).", cheapest_credible_response_if_we_succeed="n/a",
         response_cost_and_speed="n/a", evidence_ids="R7-E-G10"),
    dict(competitor_id="CM12", name="Manual trackers (Recur, SubFlow, サブマネ!, サブスク管理-固定費の把握, etc.)", **{"class": "Subscription tracker (manual)"}, geography="Japan storefronts",
         user_scale=U, paid_users=U, subscription_detection="Manual entry", cross_provider_coverage="Any (user-entered)", cancel_instructions=U, cancel_on_behalf=NF,
         bill_negotiation="n/a", verification="None", bank_linking="No", email_linking="No", price="Free to about $4 one-off", business_model="One-off or ads",
         distribution="App stores", moat="None", japan_status="Listed", evidence_strength="listings plus blog",
         how_we_lose="It sets the price of reminders at about zero.", cheapest_credible_response_if_we_succeed="n/a", response_cost_and_speed="n/a", evidence_ids="R7-E-G10"),
    dict(competitor_id="CM13", name="Cancellation guide sites (解約.com; SEO how-to sites)", **{"class": "J3 guides"}, geography="Japan", user_scale=U, paid_users="n/a",
         subscription_detection="None", cross_provider_coverage="Many services (count UNKNOWN)", cancel_instructions="Yes, with source links and AI summaries",
         cancel_on_behalf=NF, bill_negotiation="n/a", verification="None", bank_linking="No", email_linking="No", price="Free", business_model="UNKNOWN (ads or affiliate presumed)",
         distribution="Search at the moment of intent", moat="Search ranking", japan_status="Active (2023 article)", evidence_strength="secondary",
         how_we_lose="They own the intent moment ('X 解約') in search and solve the most-reported friction (finding the page) free. This undercuts both C02 revenue and H1 acquisition.",
         cheapest_credible_response_if_we_succeed="Copy any public playbook content.", response_cost_and_speed="Very low. Inference.", evidence_ids="R7-E-G11;R7-E-A03"),
    dict(competitor_id="CM14", name="Consumer centres and the 188 hotline (消費生活センター)", **{"class": "Public service (J4 advice, J6 mediation)"}, geography="Japan",
         user_scale="1.006M consultations (FY2025, all topics)", paid_users="n/a", subscription_detection="n/a", cross_provider_coverage="All", cancel_instructions="Advice",
         cancel_on_behalf="Mediation (あっせん); scope not researched here", bill_negotiation="n/a", verification="n/a", bank_linking="n/a", email_linking="n/a", price="Free",
         business_model="Public", distribution="188; local centres", moat="Public authority and trust", japan_status="Active", evidence_strength="government (extracts)",
         how_we_lose="For the obstruction and dispute cases where friction is worst, a free, trusted public channel already acts, and a paid agent would compete with it.",
         cheapest_credible_response_if_we_succeed="n/a", response_cost_and_speed="n/a", evidence_ids="R7-E-A06;R7-E-A10"),
    dict(competitor_id="CM15", name="Rocket Money (formerly Truebill; Rocket Companies)", **{"class": "Foreign scaled analogue"}, geography="US (Canada conflicting)",
         user_scale="10M+ app users (fact sheet); 2.5M members at 2021 acquisition", paid_users="Not disclosed in extracts",
         subscription_detection="Bank and card aggregation", cross_provider_coverage="US merchants", cancel_instructions="Yes",
         cancel_on_behalf="Yes: concierge team contacts merchants; 2-10 business days typical; nearly 2.5M cancellations cumulative",
         bill_negotiation="Yes; fee 35-60% of first-year savings", verification="Status e-mails; charge monitoring (extent UNKNOWN)", bank_linking="Yes",
         email_linking=U, price="Premium $3-12/month", business_model="Premium subscription plus negotiation fees; part of a mortgage group",
         distribution="US consumer marketing; Rocket ecosystem", moat="Scale, brand, operations (not tested here)", japan_status="Not available",
         evidence_strength="company-reported (SEC filings, help pages, fact sheet) plus secondary",
         how_we_lose="Not a Japanese competitor. As a precedent it shows the model works in the US with a contractual limited power of attorney, human operations and premium plus negotiation revenue. Cancellations per user are low (about 0.25 cumulative).",
         cheapest_credible_response_if_we_succeed="Not applicable in Japan (no presence).", response_cost_and_speed="n/a",
         evidence_ids="R7-E-G13;R7-E-G14;R7-E-G15;R7-E-G16;R7-E-G17;R7-E-G18;R7-E-G19;R7-E-G20;R7-E-G21"),
    dict(competitor_id="CM16", name="Trim (OneMain Financial)", **{"class": "Foreign analogue (absorbed)"}, geography="US", user_scale=U, paid_users=U,
         subscription_detection="Bank linking (historic)", cross_provider_coverage="US", cancel_instructions=U, cancel_on_behalf="Historic (UNKNOWN scope)",
         bill_negotiation="Now only for OneMain loan customers", verification=U, bank_linking="Yes", email_linking=U, price="Free (OneMain customers)",
         business_model="Retention feature for a lender", distribution="OneMain", moat="None as standalone", japan_status="Not available",
         evidence_strength="company PDF plus secondary",
         how_we_lose="A precedent for the 'feature, not company' outcome: the standalone consumer service ended inside a lender.",
         cheapest_credible_response_if_we_succeed="n/a", response_cost_and_speed="n/a", evidence_ids="R7-E-G22"),
    dict(competitor_id="CM17", name="Whatssub (왓섭, Korea)", **{"class": "Foreign direct analogue"}, geography="Korea", user_scale=U, paid_users=U,
         subscription_detection="Scraping of users' accounts", cross_provider_coverage="1,365 services identifiable (829 subscriptions plus 536 fixed costs); as-of date UNKNOWN",
         cancel_instructions="Yes", cancel_on_behalf="'One-touch' cancellation for 1,213 services (execution model unclear)", bill_negotiation=U, verification=U,
         bank_linking="Scraping", email_linking=U, price=U, business_model=U, distribution=U, moat=U, japan_status="Japan launch not found; overseas entry 'under review' (2021-23)",
         evidence_strength="secondary (Korean media)",
         how_we_lose="A foreign entrant with an existing cancellation playbook could enter Japan if a startup proves demand.",
         cheapest_credible_response_if_we_succeed="Localise and enter.", response_cost_and_speed="Medium; 6-18 months. Inference.", evidence_ids="R7-E-G23"),
    dict(competitor_id="CM18", name="Unsub.ai", **{"class": "Guide-only app (foreign)"}, geography="UNKNOWN storefronts", user_scale=U, paid_users=U,
         subscription_detection="Manual; no bank or e-mail", cross_provider_coverage="Guides for 30+ services", cancel_instructions="Step-by-step guides",
         cancel_on_behalf="No (explicitly)", bill_negotiation="No", verification="No", bank_linking="No", email_linking="No", price=U, business_model=U,
         distribution="App stores", moat="None", japan_status=U, evidence_strength="app-listing mirror",
         how_we_lose="Shows that a guide-plus-reminder product is cheap to ship (released 2026-07-05).", cheapest_credible_response_if_we_succeed="n/a",
         response_cost_and_speed="n/a", evidence_ids="R7-E-G24"),
    dict(competitor_id="CM19", name="General AI agents (ChatGPT agent mode and similar)", **{"class": "Horizontal agent"}, geography="Global (Japan availability of agent mode UNKNOWN)",
         user_scale=U, paid_users=U, subscription_detection="None native", cross_provider_coverage="Any web flow in the user's own session",
         cancel_instructions="Can navigate", cancel_on_behalf="Acts in the user's session, under supervision", bill_negotiation="No", verification="No",
         bank_linking="No", email_linking="Possible via connectors (not researched)", price="Bundled in ChatGPT Plus/Pro", business_model="General AI subscription",
         distribution="Huge installed base", moat="Model and distribution", japan_status=U, evidence_strength="low-reliability secondary",
         how_we_lose="It commoditises the 'AI navigates the web cancellation flow' step (C03) at zero marginal price for users who already pay. It does not cover phone, written or in-person routes.",
         cheapest_credible_response_if_we_succeed="Already available; nothing needed.", response_cost_and_speed="Zero.", evidence_ids="R7-E-G27"),
]
