"""R-007 permission and legal matrix (05_PERMISSION_AND_LEGAL_MATRIX.csv).

NOT LEGAL ADVICE. Each row separates the TYPE of constraint (law / provider contract / technical
restriction / unknown), what the extracts establish, what they do not, and the question Japanese
counsel must answer (experiment E5). 'Design implication' states the conservative operating
boundary this research packet assumes until counsel answers; it is not a legal conclusion.
"""

FIELDS = ["row_id", "topic", "constraint_type", "instrument_or_source", "what_extracts_establish", "what_is_not_established",
          "applies_to_jobs", "applies_to_concepts", "applies_to_routes", "status", "conservative_design_implication",
          "counsel_question", "evidence_ids"]

ROWS = [
    dict(row_id="L01", topic="Agency basics: agent vs messenger", constraint_type="law", instrument_or_source="Civil Code Art. 99, 643 (doctrine via textbooks)",
         what_extracts_establish="An agent's declaration within authority binds the principal. A messenger conveys the principal's own decision. Authority can be granted by mandate.",
         what_is_not_established="Whether a provider must accept a cancellation conveyed by a company messenger or agent, and what proof of authority suffices.",
         applies_to_jobs="J4", applies_to_concepts="C04;C05", applies_to_routes="E-class routes (RM11-RM12, RM14, RM17-RM19, RM21-RM22)", status="unresolved",
         conservative_design_implication="Model the service as a messenger conveying the user's own final decision, with a signed, timestamped instruction kept as evidence. No discretion on the user's behalf.",
         counsel_question="Is a cancellation notice conveyed by a company acting as 使者 (or as 代理人 under a written 委任) effective against a provider without the provider's consent? What form of authority (written, electronic, identity-verified) is needed?",
         evidence_ids="R7-E-E01"),
    dict(row_id="L02", topic="Provider terms restricting who may act", constraint_type="provider contract", instrument_or_source="docomo proxy rules; かんぽ生命 agent procedure; Netflix household; U-NEXT ID terms",
         what_extracts_establish="docomo: proxies for individual contracts are family-only (unverified extract). かんぽ: agent's relationship plus a possible call to the policyholder. Netflix: household-only use. U-NEXT: no third-party use of IDs.",
         what_is_not_established="Whether 'holder-only' or 'family-only' rules are enforceable against a consumer's chosen agent, including under Consumer Contract Act Art. 10 (unfair terms), and how the planned obstruction ban treats refusal of a duly authorised agent.",
         applies_to_jobs="J4", applies_to_concepts="C03;C04;C05", applies_to_routes="RM03;RM04;RM07;RM13;RM22", status="unresolved",
         conservative_design_implication="Assume providers may refuse company agents. Design for family-assisted or user-performed actions (B), with the company preparing, timing and tracking.",
         counsel_question="Can a provider lawfully refuse a cancellation from a consumer's written-authorised company agent? Would such a refusal be 'refusing a cancellation' under the proposed Consumer Contract Act amendment?",
         evidence_ids="R7-E-C10;R7-E-C19;R7-E-C22;R7-E-C23"),
    dict(row_id="L03", topic="Attorney Act Art. 72: conveying vs negotiating", constraint_type="law", instrument_or_source="弁護士法72条; 退職代行 commentary; Supreme Court 1971-07-14 and 1963-06-13 (via doctrine)",
         what_extracts_establish="Commentary: conveying a person's own decision is lawful for a non-lawyer; negotiating terms is not. The 事件性 requirement is contested. Contracts breaching Art. 72 are void.",
         what_is_not_established="Whether a routine, undisputed subscription cancellation by a paid company is a 'legal matter'. Whether handling retention offers, fee explanations or effective-date disagreements crosses into negotiation.",
         applies_to_jobs="J4;J6", applies_to_concepts="C04;C05;C06;C09", applies_to_routes="All C/E routes", status="unresolved",
         conservative_design_implication="Conveyance only. No negotiation of fees, dates, refunds or retention terms. Stop and return control to the user at any disagreement.",
         counsel_question="For a paid service that conveys a consumer's undisputed cancellation decision, where exactly is the Art. 72 line, and which scripts or behaviours (e.g. answering retention offers, confirming effective dates) cross it?",
         evidence_ids="R7-E-E02;R7-E-E04"),
    dict(row_id="L04", topic="Official reasoning on Art. 72 for tech services", constraint_type="law", instrument_or_source="MOJ guidance 2023-08-01 (AI contract review)",
         what_extracts_establish="Three cumulative elements: remuneration, 事件性, and legal affairs requiring expertise. Undisputed ordinary contracts are treated as lacking 事件性 in that context.",
         what_is_not_established="Whether this reasoning extends to services that act toward a counterparty.", applies_to_jobs="J4", applies_to_concepts="C03;C04;C05",
         applies_to_routes="All", status="unresolved", conservative_design_implication="Do not rely on the MOJ guidance as authorisation. Cite it only as context in the counsel brief.",
         counsel_question="Does the 2023 MOJ 事件性 reasoning carry over to an agent that sends undisputed cancellation notices to providers?", evidence_ids="R7-E-E05"),
    dict(row_id="L05", topic="Referral to lawyers (非弁提携)", constraint_type="law", instrument_or_source="弁護士法 (non-lawyer tie-ups); the モームリ case (2025-26)",
         what_extracts_establish="A resignation-agency operator was searched (2025-10) and its former head indicted (2026-02-24) in connection with paid lawyer referrals.",
         what_is_not_established="Outcome of the case. Which referral structures are safe.", applies_to_jobs="J6", applies_to_concepts="C04;C05;C09", applies_to_routes="n/a",
         status="established-in-extract (event); unresolved (rule)",
         conservative_design_implication="Never receive fees for referring disputes. Send J6 cases to free public channels (188) or unpaid lawyer listings.",
         counsel_question="What dispute-escalation design (if any) is permissible for a non-lawyer cancellation service, and how must any lawyer partnership be structured?",
         evidence_ids="R7-E-E03"),
    dict(row_id="L06", topic="Bill negotiation (C06)", constraint_type="law", instrument_or_source="弁護士法72条 (analogy); 電気通信事業法 27-3 fee caps",
         what_extracts_establish="Negotiation is the side of the resignation-agency line that commentary treats as unlawful for non-lawyers. Telecom exit fees are already capped (¥1,000 mobile; about one month's fee for fixed lines).",
         what_is_not_established="Whether commercial price negotiation with a telco or ISP, without any dispute, has 事件性. The size of retention discounts in Japan.",
         applies_to_jobs="J2;J4", applies_to_concepts="C06", applies_to_routes="RM13;RM14", status="unresolved",
         conservative_design_implication="Treat C06 as legally high-risk and economically small in Japan until counsel and data say otherwise.",
         counsel_question="Is negotiating a lower recurring price with a telco or ISP on a consumer's behalf, for a success fee, a 'legal matter' under Art. 72?",
         evidence_ids="R7-E-E02;R7-E-E08"),
    dict(row_id="L07", topic="Cancellation fees (Consumer Contract Act Art. 9; 2023 amendment)", constraint_type="law", instrument_or_source="消費者契約法 9条; 2023-06-01 amendments",
         what_extracts_establish="Charges above 'average damages' are void. Businesses have an effort duty to explain the basis of fees.",
         what_is_not_established="How often subscription fees in the route sample exceed average damages.", applies_to_jobs="J6", applies_to_concepts="C05",
         applies_to_routes="RM11;RM14", status="established-in-extract",
         conservative_design_implication="Show the fee and its stated basis before acting (informed consent). Never contest a fee. That is J6, so refer out.",
         counsel_question="Can the service tell users that a fee 'may be contestable' without giving legal advice?", evidence_ids="R7-E-E07;R7-E-C08;R7-E-C11"),
    dict(row_id="L08", topic="Planned obstruction ban (Consumer Contract Act reform)", constraint_type="law", instrument_or_source="CAA expert committee interim summary (2026-08/09); review meetings 2026-07",
         what_extracts_establish="Proposed: ban misrepresentation, refusal, unreasonable delay and deception or intimidation in cancellations; injunctions by qualified consumer organisations; effort duties on methods, disclosure and renewal notices. Bill as early as the next ordinary Diet session.",
         what_is_not_established="Final text and timing. Whether phone-only or complex flows are covered. Whether refusing an agent counts as refusal.",
         applies_to_jobs="J3;J4", applies_to_concepts="C02;C03;C04;C05", applies_to_routes="E-class routes", status="unresolved (proposal)",
         conservative_design_implication="Plan for the hard-route friction to shrink from about 2027-28 among compliant providers. Do not build a business whose only value is obstruction.",
         counsel_question="On the current drafts, which of the E-class route behaviours (phone-only, in person, written) would be unlawful after reform?",
         evidence_ids="R7-E-A17;R7-E-E13"),
    dict(row_id="L09", topic="定期購入 rules (Specified Commercial Transactions Act, 2022)", constraint_type="law", instrument_or_source="特商法 12条の6; anti-obstruction misrepresentation ban",
         what_extracts_establish="Final-confirmation display duties; ban on misleading displays; ban on misrepresentation to obstruct cancellation.",
         what_is_not_established="Whether a non-lawyer service may help consumers invoke statutory rescission.", applies_to_jobs="J4;J6", applies_to_concepts="C04;C05",
         applies_to_routes="P1 sellers (not sampled)", status="established-in-extract",
         conservative_design_implication="Help users cancel within the seller's stated process. Invoking statutory rescission is legal action, so refer to 188.",
         counsel_question="Can a non-lawyer service send a seller a consumer's cancellation that cites the seller's statutory duties, without negotiating?",
         evidence_ids="R7-E-E06"),
    dict(row_id="L10", topic="Telecom fee caps", constraint_type="law", instrument_or_source="電気通信事業法 27条の3 (2019-10; 2022-07)",
         what_extracts_establish="Mobile: 2-year maximum term and ¥1,000 fee cap. Fixed: fee capped at about one month's charge.",
         what_is_not_established="Legacy-contract share.", applies_to_jobs="J2;J4", applies_to_concepts="C04;C06;C08", applies_to_routes="RM13;RM14",
         status="established-in-extract", conservative_design_implication="Small money at stake per telco exit. Value lies in convenience, not savings.",
         counsel_question="n/a (factual)", evidence_ids="R7-E-E08"),
    dict(row_id="L11", topic="Personal information (APPI)", constraint_type="law", instrument_or_source="個人情報保護法 (general duties)",
         what_extracts_establish="Purpose specification and notice; no out-of-purpose use or third-party provision without consent (exceptions apply); security measures.",
         what_is_not_established="Rules for credential custody, call recordings, sharing outcomes with providers, and pseudonymised or anonymised reuse for an outcome graph (M1).",
         applies_to_jobs="J1;J4;J5", applies_to_concepts="C01-C09", applies_to_routes="All", status="unresolved (specifics)",
         conservative_design_implication="Specify 'improving cancellation routes' as a purpose at collection. Store no provider credentials. Keep outcome records at route level (provider × rail × result), not person level.",
         counsel_question="Can route-level outcome data derived from user cases be retained and used to improve service for other users, and in what processed form?",
         evidence_ids="R7-E-E10"),
    dict(row_id="L12", topic="Bank-account data", constraint_type="law", instrument_or_source="銀行法 (電子決済等代行業, 2018)",
         what_extracts_establish="Registration and bank contracts are required for account-information services. Bank reference APIs are widely available.",
         what_is_not_established="Cost and time of registration for a startup. Partner terms (Moneytree/MUFG, Money Forward).", applies_to_jobs="J1;J5",
         applies_to_concepts="C01;C05;C07;C09", applies_to_routes="n/a", status="established-in-extract",
         conservative_design_implication="No bank linkage in any first test. Later, only via a registered partner, accepting dependence on a competitor-owned pipe.",
         counsel_question="Is verification-only access (did charge X recur?) subject to the same registration as full account aggregation?",
         evidence_ids="R7-E-E09;R7-E-G07;R7-E-G08"),
    dict(row_id="L13", topic="Card data", constraint_type="technical restriction", instrument_or_source="METI card-API materials; industry practice",
         what_extracts_establish="Major card data links mostly rely on screen-scraping, and no standard card API exists.",
         what_is_not_established="Whether any registration applies to card-data aggregation. Card companies' terms on scraping.", applies_to_jobs="J1;J5",
         applies_to_concepts="C01;C05", applies_to_routes="n/a", status="unresolved",
         conservative_design_implication="Avoid card-credential custody. Use user-uploaded statements or screenshots in tests.",
         counsel_question="What legal and contractual exposure does storing card-site credentials for scraping create?", evidence_ids="R7-E-E09"),
    dict(row_id="L14", topic="E-mail receipts", constraint_type="provider contract", instrument_or_source="Google API user-data policy (restricted scopes; CASA)",
         what_extracts_establish="gmail.readonly is restricted. Server-side processing needs an annual CASA Tier 2 assessment (about $500 a year per a secondary source).",
         what_is_not_established="Outlook and Yahoo! Mail rules. Japanese template coverage.", applies_to_jobs="J1;J5", applies_to_concepts="C01;C05",
         applies_to_routes="RM01;RM02 (receipts)", status="established-in-extract",
         conservative_design_implication="Not for a first test. Use user-forwarded receipts instead.", counsel_question="n/a (platform policy)", evidence_ids="R7-E-D01"),
    dict(row_id="L15", topic="Platform-billed subscriptions", constraint_type="technical restriction", instrument_or_source="Apple and Google developer capabilities",
         what_extracts_establish="Apple: only the user or Apple support can cancel. Google: the developer can cancel via API. No third-party path.",
         what_is_not_established="Apple's own documentation.", applies_to_jobs="J4", applies_to_concepts="C03;C04", applies_to_routes="RM01;RM02",
         status="established-in-extract", conservative_design_implication="Guide only. The user cancels in Settings or Play.", counsel_question="n/a",
         evidence_ids="R7-E-B03;R7-E-B04"),
    dict(row_id="L16", topic="Credential use by a third party", constraint_type="provider contract", instrument_or_source="Netflix household terms; U-NEXT ID terms",
         what_extracts_establish="Account use is restricted to the household or member. Third-party ID use is prohibited (U-NEXT).",
         what_is_not_established="Whether a one-off cancellation login by an agent breaches these terms or is tolerated.", applies_to_jobs="J4",
         applies_to_concepts="C03;C04", applies_to_routes="RM03;RM04", status="unresolved",
         conservative_design_implication="No credential-based execution. The user logs in (B). Any automation runs in the user's own session under their control.",
         counsel_question="Does a user-supervised agent acting in the user's own logged-in session count as third-party use under typical Japanese ID terms?",
         evidence_ids="R7-E-C22;R7-E-C23"),
    dict(row_id="L17", topic="Switching-embedded cancellation", constraint_type="law", instrument_or_source="Electricity retail switching; MNP one-stop (2023)",
         what_extracts_establish="The new electricity retailer cancels the old contract on the customer's consent. MNP one-stop needs the user's consent in the old carrier's portal.",
         what_is_not_established="Whether a non-supplier intermediary can trigger these processes.", applies_to_jobs="J4", applies_to_concepts="C08",
         applies_to_routes="n/a (mechanisms)", status="established-in-extract",
         conservative_design_implication="Per the extracts, on-behalf cancellation is established practice when the gaining provider performs it. A C08 design would therefore run through the gaining provider.",
         counsel_question="n/a", evidence_ids="R7-E-C20;R7-E-C21"),
    dict(row_id="L18", topic="US limited power of attorney model", constraint_type="unknown", instrument_or_source="Rocket Money ToS (via news)",
         what_extracts_establish="Rocket Money users grant a limited POA plus debit/credit authority (US).",
         what_is_not_established="Any Japanese equivalent's effectiveness or provider acceptance.", applies_to_jobs="J4;J6", applies_to_concepts="C04;C05;C06;C09",
         applies_to_routes="n/a", status="unresolved", conservative_design_implication="Do not copy US terms. Draft from Japanese counsel's answer to L01-L03.",
         counsel_question="Is a standing (not per-cancellation) authorisation in app terms effective for Japanese cancellations?", evidence_ids="R7-E-G19"),
    dict(row_id="L19", topic="Bereavement and heirs", constraint_type="law", instrument_or_source="Inheritance rules (lawyer commentary)",
         what_extracts_establish="Cancelling a deceased person's subscription may count as a dispositive act implying acceptance of the inheritance (a risk to renunciation).",
         what_is_not_established="Prevalence. Provider bereavement procedures.", applies_to_jobs="J1;J4", applies_to_concepts="C04;C05", applies_to_routes="n/a (P4)",
         status="unresolved", conservative_design_implication="Exclude P4 from the first test. It sits close to legal advice.",
         counsel_question="Can a non-lawyer service help heirs identify (not cancel) a deceased person's subscriptions without legal-advice exposure?", evidence_ids="R7-E-E11;R7-E-A11"),
    dict(row_id="L20", topic="Seniors' capacity and family authority", constraint_type="unknown", instrument_or_source="Not researched",
         what_extracts_establish="Nothing (no source).", what_is_not_established="When a family member may cancel for an elderly parent without guardianship (成年後見); provider practice.",
         applies_to_jobs="J4", applies_to_concepts="C04", applies_to_routes="RM13 (family-only proxy)", status="unresolved",
         conservative_design_implication="P3 tests use the adult child as the user acting on their own or the parent's explicit written instruction, never on presumed authority.",
         counsel_question="What authority does an adult child need to cancel a capable parent's subscriptions, and what changes if capacity is in doubt?",
         evidence_ids="R7-E-A06"),
    dict(row_id="L21", topic="Registration for a cancellation-agent business", constraint_type="unknown", instrument_or_source="No regime found",
         what_extracts_establish="No specific licence regime for a consumer cancellation agent was found.", what_is_not_established="Whether any licence applies; no path found ≠ none required.",
         applies_to_jobs="J4", applies_to_concepts="C04;C05", applies_to_routes="n/a", status="unresolved",
         conservative_design_implication="Treat as unknown; part of E5.", counsel_question="Does any registration or licence regime apply to a paid consumer cancellation-messenger service?",
         evidence_ids="R7-E-G12"),
    dict(row_id="L22", topic="Marketing claims", constraint_type="unknown", instrument_or_source="FTC DoNotPay order (US analogy); 景品表示法 not researched",
         what_extracts_establish="The US regulator penalised unsupported 'robot lawyer' claims (2025-01).", what_is_not_established="Japanese advertising-law exposure.",
         applies_to_jobs="All", applies_to_concepts="C03;C04;C05;C09", applies_to_routes="n/a", status="unresolved",
         conservative_design_implication="No 'AI lawyer' or 'cancels anything' claims. State success rates only from measured data.",
         counsel_question="Which claims about cancellation success and AI capability are permissible under Japanese advertising law?", evidence_ids="R7-E-E12"),
]
