"""R-007 concept register (07) and hypothesis register (08). Concepts are kept separate; none is forced to win."""

CONCEPT_FIELDS = ["concept_id", "concept", "jobs_served", "route_classes_served", "payer", "economics_illustrative", "legal_exposure",
                  "cheapest_incumbent_response", "moat_candidate", "status", "reason", "evidence_ids"]

CONCEPTS = [
    dict(concept_id="R007-C01", concept="Subscription dashboard (tracker)", jobs_served="J1, J2", route_classes_served="n/a",
         payer="Consumer subscription (¥280-540/month anchors)", economics_illustrative="+¥2,307 to +¥5,984 per paying user-year; payback never (tight) to 4 months (loose)",
         legal_exposure="Low-medium (APPI; bank-data registration if linked)", cheapest_incumbent_response="Already sold by MF, Moneytree and Zaim; platform lists free",
         moat_candidate="M2 (feature)", status="Not pursued", reason="Occupied and copyable (stop condition 7 effectively triggered)",
         evidence_ids="R7-E-G02;R7-E-G05;R7-E-G09;R7-E-G10;R7-E-D03"),
    dict(concept_id="R007-C02", concept="Cancellation guide / router", jobs_served="J3", route_classes_served="All (information only)",
         payer="UNKNOWN (ads or affiliate; no source)", economics_illustrative="Revenue UNKNOWN in every scenario", legal_exposure="Low",
         cheapest_incumbent_response="Free guide sites (解約.com) and search already own intent", moat_candidate="M3 (feature)", status="Not pursued",
         reason="Only durable value would be a static guide (stop condition 6 for web routes)", evidence_ids="R7-E-G11;R7-E-A03"),
    dict(concept_id="R007-C03", concept="AI-assisted cancellation navigator (user-run handoff)", jobs_served="J3, J4 (user executes)", route_classes_served="B",
         payer="Consumer subscription", economics_illustrative="+¥2,243 to +¥5,886 per user-year, driven by subscription revenue not cancellations",
         legal_exposure="Low-medium (claims; provider terms if the agent touches sessions)", cheapest_incumbent_response="General AI agents already navigate web flows; PFMs add links",
         moat_candidate="None", status="Not pursued", reason="Commoditised by general agents and guides; user still authenticates", evidence_ids="R7-E-G27;R7-E-C24"),
    dict(concept_id="R007-C04", concept="On-behalf cancellation concierge", jobs_served="J4", route_classes_served="E (hard routes), if permitted",
         payer="Consumer per-cancellation fee (untested)", economics_illustrative="−¥763 to +¥475 per user-year; payback never in both; human-minute budget negative at ¥500, about 123 min at ¥1,500",
         legal_exposure="High until E5 (Art. 72; provider acceptance)", cheapest_incumbent_response="Free 188 for obstruction cases; providers' holder-only rules",
         moat_candidate="M1 (conditional, hard routes)", status="Parked: gated by E5", reason="Permission unresolved; frequency low; fee economics thin",
         evidence_ids="R7-E-C10;R7-E-E02;R7-E-E04;R7-E-G17"),
    dict(concept_id="R007-C05", concept="Cancellation + verified billing stop", jobs_served="J4, J5", route_classes_served="E (if permitted) + B; verification on card/bank rails",
         payer="Consumer subscription + fee, or partner", economics_illustrative="+¥2,136 to +¥6,628 per user-year, but only because of the tracker subscription; the subscription is not justified by cancellations alone (paradox flag = yes in both)",
         legal_exposure="As C04, plus data (L11, L12)", cheapest_incumbent_response="MF and Moneytree already see whether charges stop (inference)",
         moat_candidate="M1 (conditional)", status="Best surviving hypothesis; parked pending E5 + PR1",
         reason="The only concept matching the differentiating job; every gate unresolved", evidence_ids="R7-E-C05;R7-E-B06;R7-E-G03"),
    dict(concept_id="R007-C06", concept="Bill negotiation", jobs_served="J2", route_classes_served="Telco/ISP", payer="Success fee (US 35-60%)",
         economics_illustrative="−¥246 to +¥575 per user-year", legal_exposure="High (L06: negotiation side of the Art. 72 analogy)",
         cheapest_incumbent_response="Telecom fee caps already compress the value", moat_candidate="None", status="Not pursued",
         reason="Legal gate and small Japanese value pool", evidence_ids="R7-E-E02;R7-E-E08;R7-E-G20"),
    dict(concept_id="R007-C07", concept="B2B2C cancellation infrastructure", jobs_served="J4, J5 for a partner's users", route_classes_served="As C05",
         payer="Issuer, bank, wallet or benefits provider", economics_illustrative="+¥0.98M to +¥129.9M per partner-year; fee floor ¥5.86-18.37 per enrolled user-month; ALL partner inputs assumed",
         legal_exposure="High (partner compliance; data)", cheapest_incumbent_response="Visa/Pinwheel and Mastercard tooling; MUFG owns Moneytree",
         moat_candidate="M6 (conditional)", status="Parked: one discoverable number (E6)", reason="Only model where low frequency helps margins; partner demand unknown",
         evidence_ids="R7-E-G07;R7-E-G25;R7-E-G26"),
    dict(concept_id="R007-C08", concept="Switching / fixed-cost optimisation", jobs_served="J2, J4 via the gaining provider", route_classes_served="Electricity, mobile (switching mechanisms)",
         payer="Gaining provider (referral)", economics_illustrative="+¥79 to +¥778 per user-year", legal_exposure="Sector rules (not researched)",
         cheapest_incumbent_response="MF fixed-cost review; comparison sites; gaining providers already cancel the old contract",
         moat_candidate="None", status="Not pursued", reason="Conflict of interest; occupied; small", evidence_ids="R7-E-G04;R7-E-C20;R7-E-C21;R7-E-H04"),
    dict(concept_id="R007-C09", concept="Full Rocket Money-style Japan financial agent", jobs_served="J1-J6", route_classes_served="All",
         payer="Premium subscription + negotiation", economics_illustrative="Not modelled as one unit (sum of C01, C05, C06 with their gates)",
         legal_exposure="Highest (J6, negotiation, data)", cheapest_incumbent_response="MF's distribution plus fixed-cost services",
         moat_candidate="None evidenced", status="Not pursued",
         reason="Transfer from the US is weak on data, authority and negotiation; the scale precedent relies on negotiation and premium revenue",
         evidence_ids="R7-E-G13;R7-E-G17;R7-E-G19"),
]

HYP_FIELDS = ["hypothesis_id", "hypothesis", "status", "support", "contradiction", "confidence", "unknown", "cheapest_falsifier",
              "decision_implication", "evidence_ids"]

HYPOTHESES = [
    dict(hypothesis_id="H01", hypothesis="A definable Japanese customer segment has material recurring subscription-management pain.", status="Partly supported (direction)",
         support="About 20% report cancellation trouble; 定期購入 about 80-98k consultations a year; forgetting common in two independent surveys",
         contradiction="Money at risk per user modest (modal ≤¥2,000/month); segment definition and prevalence unmeasured", confidence="Medium (direction); low (magnitude)",
         unknown="Probability-sample prevalence; segment boundaries", cheapest_falsifier="PR1", decision_implication="Necessary but not sufficient; cannot carry continuation alone",
         evidence_ids="R7-E-A01;R7-E-A04;R7-E-A16;R7-E-A14"),
    dict(hypothesis_id="H02", hypothesis="Cancellation execution, rather than tracking, is the principal residual job.", status="Not supported",
         support="Hard-route frictions exist (phone, in-person, written)", contradiction="Top-cited trouble is finding the route (46.0%); forgetting is the common pain",
         confidence="Medium against", unknown="Frequency of hard-route cases per user", cheapest_falsifier="PR1", decision_implication="Reframes the product toward J1/J3, which are occupied",
         evidence_ids="R7-E-A03;R7-E-A16;R7-E-A05"),
    dict(hypothesis_id="H03", hypothesis="Strong free substitutes do not already solve that job.", status="Contradicted for easy routes; unresolved for hard routes",
         support="No Japanese on-behalf service found", contradiction="Platform lists, guides, PFMs and 188 cover J1/J3/J6; B-class routes are self-serve",
         confidence="High (easy routes)", unknown="Billing-rail mix of the target segment", cheapest_falsifier="PR1 rail reconstruction",
         decision_implication="Stop condition 1 effectively triggered for digital stackers (P2)", evidence_ids="R7-E-G12;R7-E-G29;R7-E-G11;R7-E-C24"),
    dict(hypothesis_id="H04", hypothesis="Enough users are willing to grant the minimum data access.", status="Unresolved",
         support="MF 17.3M and Moneytree about 6.5M users link accounts", contradiction="Those users grant access to incumbents, not a startup",
         confidence="Low", unknown="Startup link conversion", cheapest_falsifier="PR1 (screen-share acceptance as a proxy)", decision_implication="Detection should be borrowed",
         evidence_ids="R7-E-G01;R7-E-G07"),
    dict(hypothesis_id="H05", hypothesis="Enough users are willing to delegate cancellation.", status="Unresolved", support="Family delegation exists (docomo family proxies)",
         contradiction="No evidence of paid delegation", confidence="Low", unknown="Delegation rate on hard routes", cheapest_falsifier="PR1 prior-behaviour questions",
         decision_implication="Gate for C04/C05", evidence_ids="R7-E-C10"),
    dict(hypothesis_id="H06", hypothesis="A third party can legally and contractually cancel a meaningful subset of subscriptions.", status="Unresolved, leaning against for company agents",
         support="Messenger reading of the resignation-agency analogy; MOJ 2023 事件性 reasoning (other context)", contradiction="docomo family-only proxies; holder or credential terms; Art. 72 contested; 2025-26 enforcement in the analogue",
         confidence="Low", unknown="Counsel's view; provider acceptance", cheapest_falsifier="E5", decision_implication="Binary gate (stop condition 2)",
         evidence_ids="R7-E-E02;R7-E-E05;R7-E-C10;R7-E-E03"),
    dict(hypothesis_id="H07", hypothesis="Cancellation can be executed reliably without excessive human support.", status="Unresolved",
         support="B routes are short; US concierge exists", contradiction="Minute budget negative at ¥500 (tight); US lead times 2-10 business days",
         confidence="Low", unknown="Minutes per hard route", cheapest_falsifier="E3", decision_implication="Stop condition 5", evidence_ids="R7-E-G18"),
    dict(hypothesis_id="H08", hypothesis="The frequency or value of cancellation is enough to support the consumer business.", status="Leaning contradicted",
         support="Backlog in year 1", contradiction="Steady state 50-67% of year 1; about 0.25 cancellations per app user cumulative at the US analogue; cancellations justify only ¥22.50-450/month",
         confidence="Medium against (illustrative)", unknown="Japanese frequency", cheapest_falsifier="PR1", decision_implication="Stop condition 4 leaning; needs recurring value",
         evidence_ids="R7-E-G17"),
    dict(hypothesis_id="H09", hypothesis="A payer exists with positive unit economics.", status="Unresolved; negative for B2C pay-per-use",
         support="C07 positive if a partner pays ≥¥5.86-18.37 per enrolled user-month", contradiction="C04 payback never; partner WTP unknown; MUFG owns Moneytree; network tooling",
         confidence="Low", unknown="Partner WTP", cheapest_falsifier="E6", decision_implication="Stop condition 10", evidence_ids="R7-E-G07;R7-E-G25"),
    dict(hypothesis_id="H10", hypothesis="Customer acquisition and retention work despite episodic usage.", status="Leaning contradicted",
         support="Intent moments exist (search for 'X 解約')", contradiction="Guides own intent; paradox; churn after the need is met",
         confidence="Low-medium against", unknown="CAC in Japan", cheapest_falsifier="Intent-traffic test (not designed; outreach)", decision_implication="Pushes toward B2B2C",
         evidence_ids="R7-E-G11"),
    dict(hypothesis_id="H11", hypothesis="A compounding data, integration or trust asset can form.", status="Unresolved (M1, M6 conditional)",
         support="Hard-route playbooks are non-public", contradiction="Web routes scrapeable; incumbents see charge stops; no provider APIs",
         confidence="Low", unknown="Learning curve; data reuse legality", cheapest_falsifier="E3 learning curve + E5 (L11)", decision_implication="Stop conditions 7, 9",
         evidence_ids="R7-E-G11;R7-E-E10"),
    dict(hypothesis_id="H12", hypothesis="Incumbents cannot cheaply erase the wedge before the company builds that asset.", status="Contradicted for easy routes; unresolved for hard routes",
         support="Hard-route human execution is costly to add", contradiction="MF could add guides in weeks; networks productising; regulation by about 2027-28",
         confidence="Medium against", unknown="Incumbent appetite for human operations", cheapest_falsifier="Watch triggers", decision_implication="Stop conditions 7, 8",
         evidence_ids="R7-E-G03;R7-E-G25;R7-E-A17"),
    dict(hypothesis_id="H13", hypothesis="Japan creates a genuine initial advantage rather than extra complexity.", status="Leaning contradicted",
         support="No local on-behalf player", contradiction="Family-only proxy rules; Art. 72; scraping-based card data; competitor-owned aggregation pipes",
         confidence="Medium against", unknown="Counsel view", cheapest_falsifier="E5", decision_implication="Japan adds complexity more than advantage",
         evidence_ids="R7-E-C10;R7-E-E09;R7-E-G07"),
    dict(hypothesis_id="H14", hypothesis="The company can expand beyond cancellation without losing consumer alignment.", status="Unresolved, leaning against",
         support="Fixed-cost review is a known adjacency", contradiction="Switching revenue comes from gaining providers (conflict); negotiation legally gated; MF already there",
         confidence="Low", unknown="—", cheapest_falsifier="n/a until a core exists", decision_implication="No credible expansion path that keeps alignment",
         evidence_ids="R7-E-G04;R7-E-C20;R7-E-E02"),
]
