"""R-007 cancellation-route matrix (04_CANCELLATION_ROUTE_MATRIX.csv).

Sample: 22 routes chosen by category coverage (work order §9) and usage evidence (e.g. the top three
SVOD services by 2025 spend share, the largest carrier, a megabrand membership gym). It is a purposive
sample, NOT a random draw. Counts by class describe the sample, not the market.

route_class = the best route class available to a startup given the evidence:
  A machine-executable through a documented permitted path (for a third party)
  B user-authenticated handoff (the user logs in or authenticates; the startup guides or deep-links)
  C human concierge may execute with authorisation (evidence that a non-family agent is accepted)
  D account holder must personally act (evidence that no agent is accepted)
  E legal / contractual route unresolved (the channel or third-party acceptance is UNKNOWN)
concierge_status records separately whether on-behalf execution by a COMPANY is evidenced:
  permitted / family-only / not stated / UNKNOWN.
Never invent cells: UNKNOWN means not found. Evidence IDs point to 02_EVIDENCE_LEDGER.csv.
"""

FIELDS = ["route_id", "provider", "category", "billing_route", "subscription_owner", "self_serve_cancel_available",
          "cancel_url_or_surface", "number_of_steps", "telephone_required", "in_person_required", "MFA_or_reauth",
          "account_holder_only_language", "proxy_or_power_of_attorney_route", "credential_sharing_allowed",
          "cancellation_deadline", "minimum_term", "early_cancel_fee", "confirmation_method",
          "future_charge_verification", "third_party_automation_feasibility", "human_concierge_feasibility",
          "evidence_source", "date", "unknowns", "route_class", "concierge_status", "route_class_rationale",
          "architecture"]

U = "UNKNOWN"
D = "2026-10-05 (access); source dates in ledger"
NOAPI = "Low: no third-party API found; a third party logging in with the user's credentials is a provider-contract issue (S5)"

ROWS = [
    dict(route_id="RM01", provider="Any App Store-billed subscription", category="Platform-billed digital", billing_route="Apple App Store",
         subscription_owner="Service provider; Apple runs billing (inference)", self_serve_cancel_available="Yes (user, in Settings)",
         cancel_url_or_surface="Settings → [Apple ID] → Subscriptions → Cancel", number_of_steps="About 5-6 taps (counted from a how-to; not observed)",
         telephone_required="No", in_person_required="No", MFA_or_reauth=U, account_holder_only_language="Only the user or Apple support can cancel (community sources)",
         proxy_or_power_of_attorney_route="None found", credential_sharing_allowed=U, cancellation_deadline=U, minimum_term=U, early_cancel_fee=U,
         confirmation_method=U, future_charge_verification="Ambiguous on the card (APPLE.COM/BILL aggregate); needs Apple-side list or receipts",
         third_party_automation_feasibility="None: developers cannot cancel; no third-party path found", human_concierge_feasibility="Guidance only",
         evidence_source="R7-E-B01;R7-E-B04;R7-E-G29", date=D, unknowns="Apple's own documentation not opened; auth prompts; confirmation e-mail",
         route_class="B", concierge_status="not stated", route_class_rationale="Only the user can act; the startup can only guide a handoff", architecture="Platform settings"),
    dict(route_id="RM02", provider="Any Google Play-billed subscription", category="Platform-billed digital", billing_route="Google Play",
         subscription_owner="Service provider; Google runs billing (inference)", self_serve_cancel_available="Yes (user, in Play)",
         cancel_url_or_surface="Google Play → Subscriptions", number_of_steps=U, telephone_required="No", in_person_required="No", MFA_or_reauth=U,
         account_holder_only_language=U, proxy_or_power_of_attorney_route="Developer-side API only", credential_sharing_allowed=U,
         cancellation_deadline=U, minimum_term=U, early_cancel_fee=U, confirmation_method=U, future_charge_verification="Card descriptor format not checked (S3 gap)",
         third_party_automation_feasibility="None for third parties; the developer can cancel via API", human_concierge_feasibility="Guidance only",
         evidence_source="R7-E-B03;R7-E-D02", date=D, unknowns="Steps; descriptor; reauth", route_class="B", concierge_status="not stated",
         route_class_rationale="The user acts in Play; no third-party route", architecture="Platform settings"),
    dict(route_id="RM03", provider="Netflix (card-billed)", category="Direct digital (SVOD; #1 by 2025 spend share)", billing_route="Card / debit / prepaid / PayPay / PayPal",
         subscription_owner="Netflix", self_serve_cancel_available="Yes (web only; not in the app)", cancel_url_or_surface="netflix.com → Account → Cancel membership",
         number_of_steps="About 4-5 (from a how-to; not observed)", telephone_required="No", in_person_required="No", MFA_or_reauth="Sign-in (e-mail and password)",
         account_holder_only_language="Household-only account use", proxy_or_power_of_attorney_route="None found", credential_sharing_allowed="Household only (not a third party)",
         cancellation_deadline="Before the next renewal date (access until the day before)", minimum_term="None found", early_cancel_fee="None ('違約金はかかりません')",
         confirmation_method=U, future_charge_verification="Card line absent next cycle (descriptor match UNKNOWN)", third_party_automation_feasibility=NOAPI,
         human_concierge_feasibility="Not needed (self-serve web)", evidence_source="R7-E-C01;R7-E-C22", date=D,
         unknowns="Confirmation e-mail; descriptor; whether support will act for an agent", route_class="B", concierge_status="not stated",
         route_class_rationale="User-run web flow; credential use by a third party conflicts with household terms", architecture="Web self-serve behind login"),
    dict(route_id="RM04", provider="U-NEXT (direct)", category="Direct digital (SVOD; #2)", billing_route="Card / carrier billing / Rakuten Pay",
         subscription_owner="U-NEXT", self_serve_cancel_available="Yes (web, including mobile browser)", cancel_url_or_surface="U-NEXT website (解約, distinct from 退会)",
         number_of_steps=U, telephone_required="No", in_person_required="No", MFA_or_reauth="Sign-in", account_holder_only_language="ID and password for the member only",
         proxy_or_power_of_attorney_route="None found", credential_sharing_allowed="No (third-party use prohibited)", cancellation_deadline=U, minimum_term=U,
         early_cancel_fee=U, confirmation_method=U, future_charge_verification="Card line, or carrier-bill line if carrier-billed", third_party_automation_feasibility=NOAPI,
         human_concierge_feasibility="Not needed", evidence_source="R7-E-C02;R7-E-C23", date=D, unknowns="Steps; deadline; confirmation",
         route_class="B", concierge_status="not stated", route_class_rationale="User-run web flow; terms bar third-party credential use", architecture="Web self-serve behind login"),
    dict(route_id="RM05", provider="Amazon Prime (incl. Prime Video)", category="Direct digital (SVOD #3; retail membership)", billing_route="Amazon (card on file)",
         subscription_owner="Amazon Japan", self_serve_cancel_available="Yes (web, app, phone, chat)", cancel_url_or_surface="Account & Lists → Prime → 会員情報を更新し、プライムをキャンセルする",
         number_of_steps="3+ (from a how-to; further confirmations UNKNOWN)", telephone_required="No (optional)", in_person_required="No", MFA_or_reauth=U,
         account_holder_only_language=U, proxy_or_power_of_attorney_route=U, credential_sharing_allowed=U, cancellation_deadline=U, minimum_term=U,
         early_cancel_fee="None; automatic pro-rata refund based on benefit use", confirmation_method=U, future_charge_verification="Card line; Amazon membership page",
         third_party_automation_feasibility=NOAPI, human_concierge_feasibility="UNKNOWN whether phone or chat support acts for an agent", evidence_source="R7-E-C03;R7-E-G28",
         date=D, unknowns="Agent acceptance on phone or chat; reauth", route_class="B", concierge_status="UNKNOWN",
         route_class_rationale="User-run; phone channel exists but agent acceptance unknown", architecture="Web self-serve behind login"),
    dict(route_id="RM06", provider="Disney+ (direct)", category="Direct digital (SVOD)", billing_route="Card (direct)", subscription_owner="Disney (direct)",
         self_serve_cancel_available="Yes", cancel_url_or_surface="My page → Account → Subscription management → Cancel", number_of_steps="About 4 (from a how-to)",
         telephone_required="No", in_person_required="No", MFA_or_reauth="Sign-in", account_holder_only_language=U, proxy_or_power_of_attorney_route=U,
         credential_sharing_allowed=U, cancellation_deadline=U, minimum_term=U, early_cancel_fee=U, confirmation_method=U,
         future_charge_verification="Card line; viewable to the end of the period", third_party_automation_feasibility=NOAPI, human_concierge_feasibility="Not needed",
         evidence_source="R7-E-C04", date=D, unknowns="Terms on credentials", route_class="B", concierge_status="not stated",
         route_class_rationale="User-run web flow", architecture="Web self-serve behind login"),
    dict(route_id="RM07", provider="Disney+ (via docomo)", category="Carrier-billed content", billing_route="docomo (dアカウント; phone bill)", subscription_owner="Via docomo (contract holder: UNKNOWN)",
         self_serve_cancel_available="Yes (My docomo)", cancel_url_or_surface="My docomo → network PIN → ご契約内容 → 解約する", number_of_steps="About 8 (from a how-to)",
         telephone_required="No", in_person_required="No", MFA_or_reauth="Yes: network PIN (ネットワーク暗証番号)", account_holder_only_language=U,
         proxy_or_power_of_attorney_route="docomo proxies family-only (line-level rule; applicability to content UNKNOWN)", credential_sharing_allowed=U,
         cancellation_deadline="Effective immediately on completion (no remaining days)", minimum_term=U, early_cancel_fee="None found; no refund",
         confirmation_method="Acceptance e-mail (受付確認メール)", future_charge_verification="Phone-bill line (not visible on card)",
         third_party_automation_feasibility="Low: network PIN re-auth", human_concierge_feasibility="Not needed for the user; a company cannot hold the PIN (inference)",
         evidence_source="R7-E-C04;R7-E-C10;R7-E-B06", date=D, unknowns="Who is the contracting party for the content", route_class="B", concierge_status="family-only",
         route_class_rationale="User authenticates with the network PIN; a different effective date from the direct route", architecture="Carrier portal with re-auth"),
    dict(route_id="RM08", provider="DAZN (annual plan, paid monthly)", category="Direct digital (sports)", billing_route="Card (direct); Apple/Google variants handled on platform",
         subscription_owner="DAZN", self_serve_cancel_available="Yes (app/web: My account → Subscription → Cancel)", cancel_url_or_surface="DAZN My account",
         number_of_steps="About 4 (from the help extract)", telephone_required="No", in_person_required="No", MFA_or_reauth="Sign-in", account_holder_only_language=U,
         proxy_or_power_of_attorney_route=U, credential_sharing_allowed=U, cancellation_deadline="Stops renewal only", minimum_term="12 months",
         early_cancel_fee="No refund; monthly payments continue to term end", confirmation_method=U,
         future_charge_verification="Charges CONTINUE by contract until term end, so absence of a charge is not the success test",
         third_party_automation_feasibility=NOAPI, human_concierge_feasibility="Not needed", evidence_source="R7-E-C05", date=D, unknowns="Confirmation",
         route_class="B", concierge_status="not stated", route_class_rationale="User-run; a term contract means verification needs the contract end date",
         architecture="Term contract (cancel ≠ charges stop)"),
    dict(route_id="RM09", provider="Spotify Premium", category="Direct digital (music)", billing_route="Card (web); also Apple, Google and carriers",
         subscription_owner="Spotify", self_serve_cancel_available="Yes (browser only; not in the app)", cancel_url_or_surface="spotify.com/account → Cancel",
         number_of_steps=U, telephone_required="No", in_person_required="No", MFA_or_reauth="Sign-in", account_holder_only_language=U, proxy_or_power_of_attorney_route=U,
         credential_sharing_allowed=U, cancellation_deadline=U, minimum_term=U, early_cancel_fee=U, confirmation_method=U,
         future_charge_verification="Card line; the account reverts to Free", third_party_automation_feasibility=NOAPI, human_concierge_feasibility="Not needed",
         evidence_source="R7-E-C06", date=D, unknowns="Steps; terms", route_class="B", concierge_status="not stated", route_class_rationale="User-run web flow",
         architecture="Web self-serve behind login"),
    dict(route_id="RM10", provider="YouTube Premium (Google-billed)", category="Direct digital (video/music)", billing_route="Google (card on file)",
         subscription_owner="Google/YouTube", self_serve_cancel_available="Yes (web; non-iOS device)", cancel_url_or_surface="youtube.com/paid_memberships → Deactivate",
         number_of_steps=U, telephone_required="No", in_person_required="No", MFA_or_reauth="Google sign-in", account_holder_only_language=U, proxy_or_power_of_attorney_route=U,
         credential_sharing_allowed=U, cancellation_deadline="Benefits continue to period end", minimum_term=U, early_cancel_fee=U, confirmation_method=U,
         future_charge_verification="Card line", third_party_automation_feasibility=NOAPI, human_concierge_feasibility="Not needed", evidence_source="R7-E-C07", date=D,
         unknowns="Steps; terms", route_class="B", concierge_status="not stated", route_class_rationale="User-run web flow", architecture="Web self-serve behind login"),
    dict(route_id="RM11", provider="Adobe Creative Cloud (annual plan, paid monthly)", category="Direct digital (software)", billing_route="Card (direct)",
         subscription_owner="Adobe", self_serve_cancel_available=U, cancel_url_or_surface=U, number_of_steps=U, telephone_required=U, in_person_required="No",
         MFA_or_reauth=U, account_holder_only_language=U, proxy_or_power_of_attorney_route=U, credential_sharing_allowed=U,
         cancellation_deadline="Windows around order and renewal (14 days; 30 days before renewal) per secondary; unconfirmed", minimum_term="12 months (annual plan)",
         early_cancel_fee="50% of remaining contract charges", confirmation_method=U, future_charge_verification="Card line; the fee charge appears after cancelling",
         third_party_automation_feasibility=NOAPI, human_concierge_feasibility="UNKNOWN", evidence_source="R7-E-C08", date=D, unknowns="Channel; steps; window rules",
         route_class="E", concierge_status="UNKNOWN", route_class_rationale="The cancellation channel was not established in the extracts",
         architecture="Term contract (cancel ≠ charges stop)"),
    dict(route_id="RM12", provider="日経電子版", category="Direct digital (news)", billing_route=U, subscription_owner="Nikkei", self_serve_cancel_available=U,
         cancel_url_or_surface=U, number_of_steps=U, telephone_required=U, in_person_required=U, MFA_or_reauth=U, account_holder_only_language=U,
         proxy_or_power_of_attorney_route=U, credential_sharing_allowed=U, cancellation_deadline="A mid-month cancel is billed for the full month (weak, one source)",
         minimum_term=U, early_cancel_fee=U, confirmation_method=U, future_charge_verification=U, third_party_automation_feasibility=U, human_concierge_feasibility=U,
         evidence_source="R7-E-C09", date=D, unknowns="Almost everything", route_class="E", concierge_status="UNKNOWN", route_class_rationale="Channel not found",
         architecture="UNKNOWN"),
    dict(route_id="RM13", provider="docomo mobile line (individual contract)", category="Telco", billing_route="docomo bill", subscription_owner="NTT docomo",
         self_serve_cancel_available="Yes (My docomo online, since 2025-03-24); also shop and phone", cancel_url_or_surface="My docomo → ドコモオンライン手続き → 解約",
         number_of_steps=U, telephone_required="No (optional)", in_person_required="No (optional)", MFA_or_reauth="dアカウント sign-in",
         account_holder_only_language="The online shop is in principle for the contract holder only", proxy_or_power_of_attorney_route="委任状 plus both IDs; proxies limited to family for individual contracts",
         credential_sharing_allowed=U, cancellation_deadline=U, minimum_term=U, early_cancel_fee="A new 契約解除料 for 'non-normal use' from 2025-03 (details UNKNOWN)",
         confirmation_method=U, future_charge_verification="Final bill, then no further bill", third_party_automation_feasibility="Low: dアカウント; holder-only online",
         human_concierge_feasibility="Not for a company: proxies are family-only (decision-critical; verify on docomo's page)", evidence_source="R7-E-C10", date=D,
         unknowns="Exact family-only wording on docomo's page; fees", route_class="B", concierge_status="family-only",
         route_class_rationale="The user can self-serve online; a commercial agent is excluded by the family-only proxy rule", architecture="Formal written agency (restricted)"),
    dict(route_id="RM14", provider="SoftBank 光", category="ISP / fibre", billing_route="SoftBank bill", subscription_owner="SoftBank",
         self_serve_cancel_available="No (phone only; not in My SoftBank or shops)", cancel_url_or_surface="Phone", number_of_steps=U, telephone_required="Yes",
         in_person_required="No", MFA_or_reauth=U, account_holder_only_language=U, proxy_or_power_of_attorney_route=U, credential_sharing_allowed=U,
         cancellation_deadline="Renewal month (24th month) to avoid the fee", minimum_term="2-year auto-renewal plan",
         early_cancel_fee="¥10,450 (contracts to 2022-06-30) or one month's base fee (from 2022-07-01); plus remaining installation instalments",
         confirmation_method=U, future_charge_verification="Final bill; equipment return", third_party_automation_feasibility="None (phone)",
         human_concierge_feasibility="UNKNOWN: whether a third-party caller is accepted", evidence_source="R7-E-C11", date=D, unknowns="Agent acceptance; call verification steps",
         route_class="E", concierge_status="UNKNOWN", route_class_rationale="Phone-only; third-party caller acceptance unknown", architecture="Phone-only with fee window"),
    dict(route_id="RM15", provider="dアニメストア", category="Carrier-billed content / direct digital", billing_route="docomo, official, app, Amazon channel, ニコニコ (6 windows)",
         subscription_owner="docomo / partners by channel", self_serve_cancel_available="Yes (site or My docomo)", cancel_url_or_surface="ご契約内容の確認・変更 → dアニメストア解約",
         number_of_steps="About 5 (from a how-to)", telephone_required="No (a phone window exists)", in_person_required="No", MFA_or_reauth="dアカウント sign-in",
         account_holder_only_language=U, proxy_or_power_of_attorney_route=U, credential_sharing_allowed=U, cancellation_deadline="Effective immediately on completion",
         minimum_term=U, early_cancel_fee=U, confirmation_method="Completion screen", future_charge_verification="Depends on the window (phone bill vs card vs Amazon)",
         third_party_automation_feasibility="Low", human_concierge_feasibility="Not needed; the hard part is identifying which of six windows holds the contract",
         evidence_source="R7-E-C12", date=D, unknowns="Terms", route_class="B", concierge_status="not stated",
         route_class_rationale="User-run; identity resolution is the main friction", architecture="Carrier portal with re-auth"),
    dict(route_id="RM16", provider="chocoZAP", category="Physical membership (gym)", billing_route="App (card on file; UNKNOWN)", subscription_owner="RIZAP group",
         self_serve_cancel_available="Yes (app)", cancel_url_or_surface="App: 解約 / 退会 / 休会", number_of_steps=U, telephone_required="No", in_person_required="No",
         MFA_or_reauth=U, account_holder_only_language=U, proxy_or_power_of_attorney_route=U, credential_sharing_allowed=U,
         cancellation_deadline="10th of the month for end-of-month cancellation", minimum_term=U, early_cancel_fee="None found; no refunds",
         confirmation_method=U, future_charge_verification="Card line absent next month", third_party_automation_feasibility=NOAPI,
         human_concierge_feasibility="Not needed", evidence_source="R7-E-C13", date=D, unknowns="Steps; terms", route_class="B", concierge_status="not stated",
         route_class_rationale="App self-serve; deadline timing is a reminder problem", architecture="Web self-serve behind login"),
    dict(route_id="RM17", provider="コナミスポーツクラブ", category="Physical membership (gym)", billing_route=U, subscription_owner="Konami Sports",
         self_serve_cancel_available="No for full termination (front desk only); plan changes online", cancel_url_or_surface="Club front desk",
         number_of_steps=U, telephone_required="No (phone not accepted)", in_person_required="Yes", MFA_or_reauth="In person (ID UNKNOWN)", account_holder_only_language=U,
         proxy_or_power_of_attorney_route=U, credential_sharing_allowed="n/a", cancellation_deadline="Monthly deadline exists (date UNKNOWN)", minimum_term=U,
         early_cancel_fee=U, confirmation_method=U, future_charge_verification="Bank or card debit absent", third_party_automation_feasibility="None",
         human_concierge_feasibility="UNKNOWN: whether a proxy may attend", evidence_source="R7-E-C14;R7-E-B05", date=D, unknowns="Proxy attendance; deadline date",
         route_class="E", concierge_status="UNKNOWN", route_class_rationale="In person only; proxy acceptance unknown", architecture="In person / written"),
    dict(route_id="RM18", provider="Oisix 定期ボックス", category="Recurring physical product (food)", billing_route=U, subscription_owner="Oisix ra daichi",
         self_serve_cancel_available="Skip: yes (My page/app). Full 解約: UNKNOWN", cancel_url_or_surface="My page / app (skip); 解約 UNKNOWN", number_of_steps=U,
         telephone_required=U, in_person_required="No", MFA_or_reauth=U, account_holder_only_language=U, proxy_or_power_of_attorney_route=U, credential_sharing_allowed=U,
         cancellation_deadline="Skip by 23:59 the day before delivery; year-end blackout", minimum_term=U, early_cancel_fee=U, confirmation_method=U,
         future_charge_verification="No next shipment and no card line", third_party_automation_feasibility=U, human_concierge_feasibility=U,
         evidence_source="R7-E-C15", date=D, unknowns="解約 channel", route_class="E", concierge_status="UNKNOWN", route_class_rationale="Cancel channel not established",
         architecture="Skip / pause ≠ cancel"),
    dict(route_id="RM19", provider="進研ゼミ (Benesse)", category="Professional / learning", billing_route=U, subscription_owner="Benesse",
         self_serve_cancel_available="No (phone only, per user reviews)", cancel_url_or_surface="Phone", number_of_steps=U, telephone_required="Yes (reviews)",
         in_person_required="No", MFA_or_reauth=U, account_holder_only_language=U, proxy_or_power_of_attorney_route=U, credential_sharing_allowed="n/a",
         cancellation_deadline="Monthly; missing it costs a month (reviews)", minimum_term=U, early_cancel_fee=U, confirmation_method=U,
         future_charge_verification="Card or bank line; no next materials", third_party_automation_feasibility="None (phone)",
         human_concierge_feasibility="UNKNOWN: whether a non-account-holder caller is accepted; the account holder is often a parent", evidence_source="R7-E-C16", date=D,
         unknowns="Current official policy (the 2026 guide PDF not read); agent acceptance", route_class="E", concierge_status="UNKNOWN",
         route_class_rationale="Phone and retention route; third-party acceptance unknown", architecture="Phone-only with retention script"),
    dict(route_id="RM20", provider="スタディサプリ (individual)", category="Professional / learning", billing_route="Card / convenience store (web); App Store",
         subscription_owner="Recruit", self_serve_cancel_available="Yes (web support); App Store billing stopped separately in Apple", cancel_url_or_surface="Support web; Apple Settings",
         number_of_steps=U, telephone_required="No", in_person_required="No", MFA_or_reauth="Sign-in", account_holder_only_language=U, proxy_or_power_of_attorney_route=U,
         credential_sharing_allowed=U, cancellation_deadline=U, minimum_term=U, early_cancel_fee=U, confirmation_method=U,
         future_charge_verification="Card line, or Apple list if App Store-billed (two actions)", third_party_automation_feasibility=NOAPI, human_concierge_feasibility="Not needed",
         evidence_source="R7-E-C17", date=D, unknowns="Steps", route_class="B", concierge_status="not stated",
         route_class_rationale="User-run; stopping use ≠ stopping App Store billing", architecture="Web self-serve behind login"),
    dict(route_id="RM21", provider="NHK reception contract", category="Regulated / quasi-statutory", billing_route="Bank debit / card / invoice (UNKNOWN)", subscription_owner="NHK",
         self_serve_cancel_available="Web only for household merge; otherwise no", cancel_url_or_surface="NHK contact centre phone, then mailed forms", number_of_steps=U,
         telephone_required="Yes (most cases)", in_person_required="No", MFA_or_reauth="Identity questions by phone", account_holder_only_language=U,
         proxy_or_power_of_attorney_route=U, credential_sharing_allowed="n/a", cancellation_deadline="n/a: cancellation allowed only on qualifying events", minimum_term="n/a",
         early_cancel_fee="n/a", confirmation_method="Mailed forms returned", future_charge_verification="Debit absent", third_party_automation_feasibility="None",
         human_concierge_feasibility="UNKNOWN", evidence_source="R7-E-C18", date=D, unknowns="Agent acceptance", route_class="E", concierge_status="UNKNOWN",
         route_class_rationale="Conditional cancellation by phone and post; third-party role unknown", architecture="Phone-only with retention script"),
    dict(route_id="RM22", provider="かんぽ生命 (life insurance)", category="Regulated (insurance)", billing_route=U, subscription_owner="Japan Post Insurance",
         self_serve_cancel_available=U, cancel_url_or_surface="Post office or branch", number_of_steps=U, telephone_required="Contact required", in_person_required=U,
         MFA_or_reauth="Intent-confirmation document; possible call to the policyholder", account_holder_only_language="Policyholder intent must be confirmed",
         proxy_or_power_of_attorney_route="委任代理人 with 委任状, the agent's relationship to the policyholder, and IDs", credential_sharing_allowed="n/a",
         cancellation_deadline=U, minimum_term=U, early_cancel_fee="Surrender value effects (not researched)", confirmation_method=U, future_charge_verification="Premium debit absent",
         third_party_automation_feasibility="None", human_concierge_feasibility="UNKNOWN whether a non-relative company can be the agent", evidence_source="R7-E-C19", date=D,
         unknowns="Non-relative agents; surrender-value advice issues", route_class="E", concierge_status="UNKNOWN",
         route_class_rationale="A formal proxy route exists, but non-relative eligibility is unknown; regulated product out of first-test scope",
         architecture="Formal written agency (restricted)"),
]
